////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated from a template.
////
////     Manual changes to this file may cause unexpected behavior in your application.
////     Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace DoAnPhanMem.Models
//{
//    using System;
//    using System.Collections.Generic;

//    public partial class Order
//    {
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//        public Order()
//        {
//            this.Oder_Detail = new HashSet<Oder_Detail>();
//        }

//        public int order_id { get; set; }
//        public int payment_id { get; set; }
//        public int delivery_id { get; set; }
//        public System.DateTime oder_date { get; set; }
//        public double total { get; set; }
//        public int acc_id { get; set; }
//        public string status { get; set; }
//        public string order_note { get; set; }
//        public string oder_address { get; set; }
//        public string note { get; set; }
//        public string oderUsername { get; set; }
//        public Nullable<int> oderPhone { get; set; }

//        public virtual Account Account { get; set; }
//        public virtual Delivery Delivery { get; set; }
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
//        public virtual ICollection<Oder_Detail> Oder_Detail { get; set; }
//        public virtual Payment Payment { get; set; }
//    }
//}
namespace DoAnPhanMem.Models
{
    using System;
    using System.Collections.Generic;

    // Product 
    public partial class Order
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Oder_Detail = new HashSet<Oder_Detail>();
        }
        public int order_id { get; set; }
        public int payment_id { get; set; }
        public int delivery_id { get; set; }
        public System.DateTime oder_date { get; set; }
        public double total { get; set; }
        public int acc_id { get; set; }
        public string status { get; set; }
        public string order_note { get; set; }
        public string oder_address { get; set; }
        public string note { get; set; }
        public string oderUsername { get; set; }
        public Nullable<int> oderPhone { get; set; }
        // Lớp Order cũng có các quan hệ với các lớp khác như Account, Delivery, Oder_Detail, và Payment. Ví dụ:
        // Account: Quan hệ một-nhiều với lớp Account, một đơn hàng thuộc về một tài khoản khách hàng.
        public virtual Account Account { get; set; }
        // Delivery: Quan hệ một-một với lớp Delivery, một đơn hàng có một phương thức giao hàng.
        public virtual Delivery Delivery { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        // Oder_Detail: Quan hệ một-nhiều với lớp Oder_Detail, một đơn hàng có thể có nhiều chi tiết đơn hàng.
        public virtual ICollection<Oder_Detail> Oder_Detail { get; set; }
        // Payment: Quan hệ một-một với lớp Payment, một đơn hàng có một phương thức thanh toán. 
        public virtual Payment Payment { get; set; }       
    }
}
